# Generated by Django 4.2.11 on 2024-05-08 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokemons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pokemon",
            options={"ordering": ["pokemon_id"]},
        ),
    ]
